/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:1c03b3ba-6af6-4203-84c8-a3cd86ce57c1",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_izn4A79Ke",
    "aws_user_pools_web_client_id": "4uev32m241n2cprmmqn5nr542v",
    "oauth": {}
};


export default awsmobile;
